version: "3.8"

services:
  app:
    container_name: goods-partner
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - GOOGLE_MAPS_API_KEY
    ports:
      - 3001:3001
    env_file:
      - compose.env
  db:
    image: postgres:14.4
    ports:
      - 5432:5432
    volumes:
      - my-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  my-vol: