// export const CALCULATE_BY_DATE = 'CALCULATE_BY_DATE';

export const ORDERS_BY_DATE = 'ORDERS_BY_DATE';
export const ROUTES_BY_DATE = 'ROUTES_BY_DATE';
export const STORES_BY_DATE = 'STORES_BY_DATE';
