server:
  port: ${PORT:3001}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
    pathmatch:
      matching-strategy: ant_path_matcher
google:
  api:
    key: ${GOOGLE_API_KEY}

grandeDolce:
  1c:
    url: ${GRANDE_DOLCE_1C_URL}

graphhopper:
  enabled: true
  osm:
    url: ${OSM_FILE_URL}
    file: ${OSM_FILE_LOCATION}
    graph: ${OSM_GRAPH_LOCATION}
  profiles:
    name: car
    vehicle: car
    weighting: fastest




