server:
  port: ${PORT:3001}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
    pathmatch:
      matching-strategy: ant_path_matcher
google:
  api:
    key: ${GOOGLE_API_KEY}

grandeDolce:
  1c:
    url: http://89.76.239.245:8080/test/odata/standard.odata/




