server:
  port: ${PORT:3001}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
    pathmatch:
      matching-strategy: ant_path_matcher

client:
  accounting:
    client-server-url: ${CLIENT_APACHE_URL} #Client-Apache-server
    server-1c-uri-prefix: ${CLIENT_1C_URI} #Base uri to 1C
    login: ${CLIENT_1C_LOGIN}
    password: ${CLIENT_1C_PASSWORD}
    documents-uri-prefix: ${CLIENT_DOCUMENTS_URI} #Local docs on Apache server

  business:
    pre-packing:
      keywords:
        - фасовк
        - фабрика
    self-service:
      keywords:
        - самовивіз
    postal:
      keywords:
        - нова пошта
        - новапошта
        -  нп
        - делівері
        - delivery
        - делівери
        - деливери
    cooler:
      keywords:
        - заморозка
    midday-delivery:
      keywords:
        - до обіду


graphhopper:
  enabled: true
  osm:
    url: ${OSM_FILE_URL}
    file: ${OSM_FILE_LOCATION}
    graph: ${OSM_GRAPH_LOCATION}
  profiles:
    name: car
    vehicle: car
    weighting: fastest

google:
  geocode:
    apiKey: ${GOOGLE_API_KEY}
    region: ua
    language: uk-UK
    boundaries:
      north: 51.0
      south: 49.5
      east: 31.5
      west: 29.5



