server:
  port: ${PORT:3001}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
    pathmatch:
      matching-strategy: ant_path_matcher
google:
  api:
    key: ${GOOGLE_API_KEY}

client:
  accounting:
    client-server-url: ${CLIENT_APACHE_URL} #Client-Apache-server
    server-1c-uri-prefix: ${CLIENT_1C_URI} #Base uri to 1C
    login: ${CLIENT_1C_LOGIN}
    password: ${CLIENT_1C_PASSWORD}
    documents-uri-prefix: ${CLIENT_DOCUMENTS_URI} #Local docs on Apache server

  business:
    pre-packing: #TODO coordinates
      address: "вулиця Київська, 34, Фастів, Київська обл., Україна, 08500"
    self-service: #TODO coordinates
      address: "вулиця Київська, 32, Фастів, Київська обл., Україна, 08500"
    postal: #TODO coordinates
      address: "вулиця Київська, 30, Фастів, Київська обл., Україна, 08500"

graphhopper:
  enabled: true
  osm:
    url: ${OSM_FILE_URL}
    file: ${OSM_FILE_LOCATION}
    graph: ${OSM_GRAPH_LOCATION}
  profiles:
    name: car
    vehicle: car
    weighting: fastest




