spring:
  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_URL}
    password: ${JDBC_DATABASE_PASSWORD}

goodspartner:
  security:
    enabled: true
    jwt:
      access-token:
        secret: ${ACCESS_TOKEN_SECRET}
        expiration: 86400000 # a day
      refresh-token:
        secret: ${REFRESH_TOKEN_SECRET}
        expiration: 604800000 # 7 days
