server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1/

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    view:
      prefix: /build/
google:
  api:
    key: ${GOOGLE_API_KEY}

