export const ORDERS_BY_DATE = 'ORDERS_BY_DATE';
export const CALCULATE_ROUTES_BY_DATE = 'ROUTES_BY_DATE';
export const UPDATE_ROUTE = 'UPDATE_ROUTE';
export const CHANGE_ROUTE_POINT_STATUS = 'CHANGE_ROUTE_POINT_STATUS';
export const CHANGE_ROUTE_STATUS = 'CHANGE_ROUTE_STATUS';
export const STORES_BY_DATE = 'STORES_BY_DATE';
export const ALL_CARS = 'ALL_CARS';
