ALTER TABLE orders ADD COLUMN ref_key VARCHAR(36) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN comment VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE grandedolce_orders ADD COLUMN ref_key VARCHAR(36) NOT NULL DEFAULT '';
ALTER TABLE grandedolce_orders ADD COLUMN comment VARCHAR(255) NOT NULL DEFAULT '';