ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_DELIVERY_ID FOREIGN KEY (delivery_id) REFERENCES deliveries (id);

ALTER TABLE grandedolce_orders
    ADD CONSTRAINT FK_GRANDEDOLCE_ORDERS_ON_DELIVERY_ID FOREIGN KEY (delivery_id) REFERENCES deliveries (id);

ALTER TABLE grandedolce_orders ADD COLUMN "car_load_id" UUID;
ALTER TABLE grandedolce_orders
    ADD CONSTRAINT FK_GRANDEDOLCE_ORDERS_ON_CAR_LOAD_ID FOREIGN KEY (car_load_id) REFERENCES car_loads (id);

ALTER TABLE car_loads
    ADD CONSTRAINT FK_CAR_LOADS_ON_DELIVERY_ID FOREIGN KEY (delivery_id) REFERENCES deliveries (id);

ALTER TABLE car_loads
    ADD CONSTRAINT FK_CAR_LOADS_ON_CAR_ID FOREIGN KEY (car_id) REFERENCES cars (id);

ALTER TABLE routes ADD COLUMN "car_id" INTEGER;

ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_CAR_ID FOREIGN KEY (car_id) REFERENCES cars (id);

ALTER TABLE grandedolce_orders ALTER COLUMN ref_key DROP NOT NULL;
ALTER TABLE grandedolce_orders ALTER COLUMN comment DROP NOT NULL;

ALTER TABLE grandedolce_addresses ALTER COLUMN latitude TYPE DECIMAL(17, 13);
ALTER TABLE grandedolce_addresses ALTER COLUMN longitude TYPE DECIMAL(17, 13);