name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    env:
      CI: ""
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      PROD_BASE_URL: ${{ vars.PROD_BASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Show env vars
        run: echo " 1 ${{ vars.PROD_BASE_URL }}  2 ${{ env.PROD_BASE_URL }} 3 ${{ env }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
          cache: 'yarn'
          cache-dependency-path: ${{ github.workspace }}/goods-partner-frontend/yarn.lock

      - name: Cache Node.js modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          cd ./goods-partner-frontend
          yarn install

      - name: Build React Project
        run: |
          cd ./goods-partner-frontend
          yarn build

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn -pl goods-partner-backend --batch-mode clean install  -Dmaven.test.skip=true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: goods-partner-backend-1.0-SNAPSHOT.jar
          path: ${{ github.workspace }}/goods-partner-backend/target/goods-partner-backend-1.0-SNAPSHOT.jar

  deployProd:
    name: Deploy to prod environment
    if: inputs.environment == 'Production'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: goods-partner-backend-1.0-SNAPSHOT.jar

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Copy backend artifact to remote host
        run: scp ./goods-partner-backend-1.0-SNAPSHOT.jar  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu

      - name: Restart Deployed artifact
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /usr/jar
            sudo sh deploy.sh

  deployDev:
    name: Deploy to dev environment
    if: inputs.environment == 'Development'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: goods-partner-backend-1.0-SNAPSHOT.jar

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Copy backend artifact to remote host
        run: scp ./goods-partner-backend-1.0-SNAPSHOT.jar  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu

      - name: Restart Deployed artifact
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /usr/jar
            sudo sh deploy.sh
