name: Deploy to AWS 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Show env vars
        env:
          CI: ""
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          PROD_BASE_URL: ${{ env.PROD_BASE_URL }}
        run: echo " 1 ${{ vars.PROD_BASE_URL }}  2 ${{ env.PROD_BASE_URL }} 3 ${{ env }}"

      - name: Build with Maven
        run: mvn --batch-mode clean install  -Dmaven.test.skip=true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: goods-partner-backend-1.0-SNAPSHOT.jar
          path: ${{ github.workspace }}/goods-partner-backend/target/goods-partner-backend-1.0-SNAPSHOT.jar

  deployProd:
    name: Deploy to prod environment
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: goods-partner-backend-1.0-SNAPSHOT.jar

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Copy backend artifact to remote host
        run: scp ${{ github.workspace }}/goods-partner-backend/target/goods-partner-backend-1.0-SNAPSHOT.jar  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu

      - name: Restart Deployed artifact
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /usr/jar
            sudo sh deploy.sh
